stages:
  prepare_data:
    cmd: python src/prepare_data.py
    deps:
      - src/prepare_data.py
    outs:
      - data/raw/data.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - src/utils.py
      - data/raw/data.csv
    outs:
      - models/best_model.pkl
      - models/scaler.pkl
      - models/feature_names.pkl
